#This is a basic workflow to help you get started with Actions

name: Building

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - main.py

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-venv python3-pip
          pip3 install -U pyinstaller
      - name: Building
        run: |
          python3 -m venv env
          ./env/bin/pip3 install -r requirements.txt
          pyinstaller --onefile --path ./env/lib/python*/site-packages main.py
  
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: |
          pip install -U pyinstaller
          python3 -m venv env
          .\env\Scripts\activate
          pip3 install -r requirements.txt
          pyinstaller.exe --onefile --path .\env\Lib\site-packages .\main.py


