#This is a basic workflow to help you get started with Actions

name: Building

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - main.py

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Env creation
        run: |
          pip3 install -U pyinstaller
          python3 -m venv env
      - name: Building Linux
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          ./env/bin/pip3 install -r requirements.txt
          pyinstaller --onefile --path ./env/lib/python*/site-packages main.py
          mv dist/main linux_build
      - name: Building Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: | 
          .\env\Scripts\activate
          pip3 install -r requirements.txt
          pyinstaller.exe --onefile --path .\env\Lib\site-packages .\main.py
          mv dist\main.exe windows_build.exe
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://api.github.com/repos/kernel-machine/apcOSC2MIDI/releases/1/assets
          # This is how it will be named on the release page. Put hatever name
          # you like, remember that they need to be different for each platform.
          # You can choose any build matrix parameters. For Rust I use the
          # target triple.
          asset_name: program-name-${{ matrix.os }}
          # The path to the file you want to upload.
          asset_path: ./*_build*
          # probably you will need to change it, but most likely you are
          # uploading a binary file
          asset_content_type: application/octet-stream