#This is a basic workflow to help you get started with Actions

name: Building

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - main.py

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
        run: pip3 install -U pyinstaller
        run : python3 -m venv env
        if: matrix.os == 'ubuntu-22.04'
          run: |
            ./env/bin/pip3 install -r requirements.txt
            pyinstaller --onefile --path ./env/lib/python*/site-packages main.py
        else:
          run: | 
            .\env\Scripts\activate
            pip3 install -r requirements.txt
            pyinstaller.exe --onefile --path .\env\Lib\site-packages .\main.py